### PR TITLE
wasapi: Workaround for the Realtek driver "Mono" bug

### LINKED ISSUE #875: Win32/WASAPI loopback: can not open stream at mono mode, paInvalidChannelCount
**Describe the bug**
`Pa_OpenStream()` return  `paInvalidChannelCount` when open stream at mono mode on a loopback device, but `Pa_IsFormatSupported()` report `paFormatIsSupported`
**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
```
// Open loopback device
    int loopback = portaudio::getDefalutLoopback();
    if (loopback < 0)
    {
        std::cout << "Error: No loopback device found" << std::endl;
        return false;
    }
    int sampleRates[] = {8000, 16000, 32000, 44100, 48000};
    PaStreamParameters loopbackParameters{};
    loopbackParameters.channelCount = 1;
    loopbackParameters.device = loopback;
    loopbackParameters.sampleFormat = paInt16;
    loopbackParameters.suggestedLatency = Pa_GetDeviceInfo(loopbackParameters.device)->defaultLowInputLatency;
    loopbackParameters.hostApiSpecificStreamInfo = NULL;
    for (int i = 0; i < 5; i++)
    {
        // Check if the format is supported
        PaError err = Pa_IsFormatSupported(&loopbackParameters, NULL, sampleRates[i]);
        if (err == paFormatIsSupported)
        {
            m_nloopbackSampleRate = sampleRates[i];
        }
    }
    err = Pa_OpenStream(&loopbackStream, &loopbackParameters, NULL, m_nloopbackSampleRate, m_frame_size * 2, paClipOff, NULL, NULL);
    if (err != paNoError)
    {
        qDebug() << "Error: sampleRate " << Pa_GetErrorText(err) << m_nloopbackSampleRate;
        return false;
    }
```

**Desktop (please complete the following information):**
 - OS: windows 10 22h2
 - PortAudio version: stable, nightly snapshot (which?), current (please give date and/or Git hash): current master branch
 - If Windows or Linux, which Host API (e.g. WASAPI): WASAPI

### PR DESCRIPTION
**Pull request by dmitrykos**
Workaround for the Realtek driver bug when driver mistakenly accepts Mono format with `IAudioClient_IsFormatSupported()` while subsequently fails in `IAudioClient_Initialize()`.

It is a long-lasting issue #875 which was resolved with a kind debugging help by @arkadijs.

Closes #875.

### CODE REVIEW

**Comment by arkadijs** [comment]
Confirming, this fixes the issue with the buggy? Realtek driver.

**Comment by dmitrykos** [comment]
@arkadijs thank you very much for testing. Now let's wait for a review from @RossBencina and @philburk to get this PR approved.

File: src/hostapi/wasapi/pa_win_wasapi.c [hunk 1]
```diff
@@ -2934,14 +2940,16 @@ static HRESULT GetAlternativeSampleFormatExclusive(IAudioClient *client, double
...
+static PaError GetClosestFormat(IAudioClient *client, const PaWasapiDeviceInfo *deviceInfo,
+    const PaStreamParameters *_params, double sampleRate, AUDCLNT_SHAREMODE shareMode,
+    WAVEFORMATEXTENSIBLE_UNION *outWavexU, BOOL output)
 {
     PaWasapiStreamInfo *streamInfo   = (PaWasapiStreamInfo *)_params->hostApiSpecificStreamInfo;
     WAVEFORMATEX *sharedClosestMatch = NULL;
     HRESULT hr                       = !S_OK;
     PaStreamParameters params        = (*_params);
     const BOOL explicitFormat        = (streamInfo != NULL) && ((streamInfo->flags & paWinWasapiExplicitSampleFormat) == paWinWasapiExplicitSampleFormat);
+    const BOOL sharedMode            = (shareMode == AUDCLNT_SHAREMODE_SHARED);
```
Comment (RossBencina) [inline src/hostapi/wasapi/pa_win_wasapi.c:2952]: maybe nicer
```suggestion
    const BOOL isSharedMode            = (shareMode == AUDCLNT_SHAREMODE_SHARED);
```

**Review by RossBencina — APPROVED** [review]
I have not tested it, but it looks OK. my main concern would be whether this could introduce a regression on other drivers. is it passing the PortAudio `pa_loopback` tests?

File: src/hostapi/wasapi/pa_win_wasapi.c (hunk 1 above)
Comment (dmitrykos) [reply src/hostapi/wasapi/pa_win_wasapi.c]: I was also thinking about it but decided to obey the style of `explicitFormat` variable. Changed to ­`is` version and also updated `explicitFormat` to play nicely together.

**Comment by dmitrykos** [comment]
> I have not tested it, but it looks OK. my main concern would be whether this could introduce a regression on other drivers. is it passing the PortAudio `pa_loopback` tests?

Great that you mentioned it! I modified workaround to exclude Input mode as this driver bug is related to Output only.

As to `pa_loopback` - it fails for WASAPI on [Loopback] device because of this #935 issue - when there is no audio sent to WASAPI internal mixer from some opened audio streams the attempt to read data from [Loopback] device will timeout i.e. `PaQa_RunInputOnly()` fails. But it has nothing to do with workaround of this PR - tested.

I propose to discuss the timeout of [Loopback] WASAPI device in #935, there we can also discuss whether a workaround needed in `pa_loopback` implementation for loopback devices which timeout without audio data collected from other opened audio streams, or perhaps PA WASAPI needs some workaround for this specific behavior.

This PR looks ok for me to commit.

File: src/hostapi/wasapi/pa_win_wasapi.c [hunk 2]
```diff
@@ -2974,6 +2982,18 @@ static PaError GetClosestFormat(IAudioClient *client, double sampleRate, const P
 
     if (hr == S_OK)
     {
+        // Workaround for the Realtek driver bug (see https://github.com/PortAudio/portaudio/issues/875):
```
Comment (philburk) [inline src/hostapi/wasapi/pa_win_wasapi.c:2985]: It would be nice to gate this change based on whether the driver is Realtek and on the version.
That would make it less likely to cause a regression on systems that do not have the Realtek bug.

File: src/hostapi/wasapi/pa_win_wasapi.c [hunk 3]
```diff
@@ -2974,6 +2982,18 @@ static PaError GetClosestFormat(IAudioClient *client, double sampleRate, const P
...
+        // IAudioClient_IsFormatSupported() accepts Mono format (mistakenly) but fails in
+        // IAudioClient_Initialize(), this bug was probably fixed because it can not be reproduced
+        // with Realtek driver version 10.0.19041.3636, 19/10/2023, affects Output mode only
+        if (output && isSharedMode && (params.channelCount == 1) && (sharedClosestMatch == NULL) &&
+            (deviceInfo->MixFormat.Format.nChannels > 1))
+        {
+            // force internal Mono to Stereo mixer
+            outWavex->Format.nChannels = 2;
```
Comment (RossBencina) [inline src/hostapi/wasapi/pa_win_wasapi.c:2993]: What effect does this line have? Does PortAudio then need to duplicate the mono stream? or does this line simply configure the mixer without changing the format of data sent to WASAPI?

File: src/hostapi/wasapi/pa_win_wasapi.c (hunk 2 above)
Comment (dmitrykos) [reply src/hostapi/wasapi/pa_win_wasapi.c:2985]: Yes, it can be gated by device name as all Realtek devices have "Realtek" string inside the name, so it can be:

```
if (strstr(device_name, "Realtek") != NULL)
{
    // workaround action goes here
}
```

File: src/hostapi/wasapi/pa_win_wasapi.c (hunk 3 above)
Comment (dmitrykos) [reply src/hostapi/wasapi/pa_win_wasapi.c:2993]: This line activates internal PA WASAPI's Mono to Stereo mixer (works as duplication of Mono stream to L and R channels, no data alteration). So WASAPI backend receives Stereo stream, user-side code sends Mono and this operation is transparent for user-code as it just keeps sending Mono data as it was meant by the code. Normally WASAPI backend would just report that 1 channel is not supported and provide 2 channel format in return but this buggy driver (as I understood it is quite widespread, even nowadays) does not do it. So we enforce 2 channels output for it.

File: src/hostapi/wasapi/pa_win_wasapi.c (hunk 2 above)
Comment (dmitrykos) [reply src/hostapi/wasapi/pa_win_wasapi.c:2985]: @philburk I implemented your proposal, would you please check.

Comment (philburk) [reply src/hostapi/wasapi/pa_win_wasapi.c:2985]: Thanks.

**Review by philburk — APPROVED** [review]

**Comment by arkadijs** [comment]
There is one problem with the latest version though: `output == 0` thus workaround never activates.

Removing `if (output &&` allows recording to proceed. Added some `printf` calls for debug:
```
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 1; output = 0
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 1; output = 0
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 1; output = 0
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 1; output = 0
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 0; output = 0
should we try Realtek workaround?
activating Realtek workaround
Słuchawki (Realtek(R) Audio) [Loopback]: trying callback API...
device name: Słuchawki (Realtek(R) Audio) [Loopback]; hr = 0; output = 0
should we try Realtek workaround?
activating Realtek workaround
Słuchawki (Realtek(R) Audio) [Loopback]: stream active: 1
Słuchawki (Realtek(R) Audio) [Loopback]: success
```

**Comment by arkadijs** [comment]
Another issue: callback API works perfectly but sync `Pa_ReadStream()` produces grabled audio which is recognizable yet sounds like a wrong format or bad interleave. Please let me know if you need the output sample or any additional debug info.

**Comment by dmitrykos** [comment]
@arkadijs thank you very much for testing again, that was typo on my side. I modified that check to !output to limit the case only to capturing devices:

```c
        if (!output && isSharedMode && (params.channelCount == 1) && (sharedClosestMatch == NULL) &&
            (deviceInfo->MixFormat.Format.nChannels > 1))
```

Would you please double check if it still works well for you to double confirm.

> callback API works perfectly but sync `Pa_ReadStream()` produces grabled audio which is recognizable yet sounds like a wrong format, clipped?

I managed to reproduce it by modifying `paex_read_write_wire.c` example which reads Loopback and writes to Speakers. I used Speakers for listening and USB DAC for playing to it with another app. It is not related to the workaround of this PR though and is an old bug. I propose to open new issue which we will close with a new PR related to this issue. Would you please open it as long as you initially found and reported this problem.

**Comment by arkadijs** [comment]
Tested latest version with `!output` and it works for me. Thanks!

Opened #945.

**Comment by dmitrykos** [comment]
> Tested latest version with `!output` and it works for me. Thanks!

Great! Lets wait for @RossBencina to resolve his question.

File: src/hostapi/wasapi/pa_win_wasapi.c [hunk 4]
```diff
@@ -2974,6 +2982,22 @@ static PaError GetClosestFormat(IAudioClient *client, double sampleRate, const P
...
+        // IAudioClient_IsFormatSupported() accepts Mono format (mistakenly) but fails in
+        // IAudioClient_Initialize(), this bug was probably fixed because it can not be reproduced
+        // with Realtek driver version 10.0.19041.3636, 19/10/2023, affects Output mode only
+        if (!output && isSharedMode && (params.channelCount == 1) && (sharedClosestMatch == NULL) &&
+            (deviceInfo->MixFormat.Format.nChannels > 1))
+        {
+            // Limit this workaround to Realtek devices only
+            if (strstr(baseDeviceInfo->name, "Realtek") != NULL)
+            {
+                // Force internal Mono to Stereo mixer
```
Comment (RossBencina) [inline src/hostapi/wasapi/pa_win_wasapi.c:2995]: I think this is less confusing:

```suggestion
                // Force our Mono to Stereo mixer mechanism
```

**Comment by RossBencina** [comment]
I'll merge this once CI passes

**Comment by arkadijs** [comment]
GHA had issues yesterday, please bump the jobs to clear CI.

**Comment by dmitrykos** [comment]
@RossBencina I merged it for you, if you do not mind, so we could go forward with other fixes.
